// <auto-generated />
using System;
using Alpaca.Data.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alpaca.Data.EFCore.Migrations
{
    [DbContext(typeof(ADbContext))]
    [Migration("20210220030323_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alpaca.Data.Entities.ConfigApp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.Property<int>("VerifyMissingDays")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ConfigApp");
                });

            modelBuilder.Entity("Alpaca.Data.Entities.ConfigAppEnvironment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConfigAppID")
                        .HasColumnType("int");

                    b.Property<int>("ConfigEnvironmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ConfigAppID", "IsDeleted");

                    b.ToTable("ConfigAppEnvironment");
                });

            modelBuilder.Entity("Alpaca.Data.Entities.ConfigEnvironment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ConfigEnvironment");
                });

            modelBuilder.Entity("Alpaca.Data.Entities.ConfigItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConfigAppID")
                        .HasColumnType("int");

                    b.Property<int>("ConfigEnvironmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ConfigAppID", "ConfigEnvironmentID", "IsDeleted");

                    b.ToTable("ConfigItem");
                });

            modelBuilder.Entity("Alpaca.Data.Entities.ConfigItemSniffer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConfigAppID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerifyMissingTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ConfigAppID", "Namespace", "IsDeleted");

                    b.ToTable("ConfigItemSniffer");
                });

            modelBuilder.Entity("Alpaca.Data.Entities.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "100",
                            CreateTime = new DateTime(2021, 2, 20, 11, 3, 22, 487, DateTimeKind.Local).AddTicks(9449),
                            CreateUserID = 0,
                            IsDeleted = false,
                            Name = "Admin",
                            UpdateTime = new DateTime(2021, 2, 20, 11, 3, 22, 488, DateTimeKind.Local).AddTicks(636),
                            UpdateUserID = 0
                        },
                        new
                        {
                            ID = 2,
                            Code = "100101",
                            CreateTime = new DateTime(2021, 2, 20, 11, 3, 22, 488, DateTimeKind.Local).AddTicks(1627),
                            CreateUserID = 0,
                            IsDeleted = false,
                            Name = "UserPermissionManagement",
                            UpdateTime = new DateTime(2021, 2, 20, 11, 3, 22, 488, DateTimeKind.Local).AddTicks(1633),
                            UpdateUserID = 0
                        },
                        new
                        {
                            ID = 3,
                            Code = "100102",
                            CreateTime = new DateTime(2021, 2, 20, 11, 3, 22, 488, DateTimeKind.Local).AddTicks(1639),
                            CreateUserID = 0,
                            IsDeleted = false,
                            Name = "UserManagemenet",
                            UpdateTime = new DateTime(2021, 2, 20, 11, 3, 22, 488, DateTimeKind.Local).AddTicks(1641),
                            UpdateUserID = 0
                        });
                });

            modelBuilder.Entity("Alpaca.Data.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Name", "IsDeleted");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateTime = new DateTime(2021, 2, 20, 11, 3, 22, 490, DateTimeKind.Local).AddTicks(3720),
                            CreateUserID = 0,
                            IsDeleted = false,
                            Name = "admin",
                            NickName = "Admin",
                            Password = "DB69FC039DCBD2962CB4D28F5891AAE1",
                            UpdateTime = new DateTime(2021, 2, 20, 11, 3, 22, 490, DateTimeKind.Local).AddTicks(3736),
                            UpdateUserID = 0
                        });
                });

            modelBuilder.Entity("Alpaca.Data.Entities.UserPermission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID", "IsDeleted");

                    b.ToTable("UserPermission");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AppID = 0,
                            CreateTime = new DateTime(2021, 2, 20, 11, 3, 22, 490, DateTimeKind.Local).AddTicks(8956),
                            CreateUserID = 0,
                            IsDeleted = false,
                            PermissionCode = "100",
                            UpdateTime = new DateTime(2021, 2, 20, 11, 3, 22, 490, DateTimeKind.Local).AddTicks(8969),
                            UpdateUserID = 0,
                            UserID = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
